FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081
 
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["/Genelife.Domain/Genelife.Domain.csproj", "Genelife.Domain/Genelife.Domain.csproj"]
RUN dotnet restore "./Genelife.Domain/Genelife.Domain.csproj"
COPY ./Genelife.Domain ./Genelife.Domain
WORKDIR "/src/Genelife.Domain"
RUN dotnet build "./Genelife.Domain.csproj" -c $BUILD_CONFIGURATION -o /app/build
 
FROM build as depbuild
WORKDIR /src
COPY ["Genelife.Inventory/Genelife.Inventory.csproj", "Genelife.Inventory/"]
RUN dotnet restore "./Genelife.Inventory/Genelife.Inventory.csproj"
COPY ./Genelife.Inventory ./Genelife.Inventory
WORKDIR "/src/Genelife.Inventory"
RUN dotnet build "./Genelife.Inventory.csproj" -c $BUILD_CONFIGURATION -o /app/build
 
FROM depbuild AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Genelife.Inventory.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
 
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Genelife.Inventory.dll"]