// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;
using Microsoft.ML.Data;

namespace GeneLife.Oracle.Core
{
    internal partial class Attractiveness
    {
        /// <summary>
        /// model input class for Attractiveness.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"F_EyeColor")]
            public string F_EyeColor { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"F_HairType")]
            public string F_HairType { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"F_Morphotype")]
            public string F_Morphotype { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"F_Intelligence")]
            public string F_Intelligence { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"F_HeightPotential")]
            public string F_HeightPotential { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"F_Age")]
            public float F_Age { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"F_Sex")]
            public string F_Sex { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"F_BehaviorPropension")]
            public string F_BehaviorPropension { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"S_EyeColor")]
            public string S_EyeColor { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"S_HairType")]
            public string S_HairType { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"S_Morphotype")]
            public string S_Morphotype { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"S_Intelligence")]
            public string S_Intelligence { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"S_HeightPotential")]
            public string S_HeightPotential { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"S_Age")]
            public float S_Age { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"S_Sex")]
            public string S_Sex { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"S_BehaviorPropension")]
            public string S_BehaviorPropension { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"Result")]
            public float Result { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Attractiveness.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"F_EyeColor")]
            public float[] F_EyeColor { get; set; }

            [ColumnName(@"F_HairType")]
            public float[] F_HairType { get; set; }

            [ColumnName(@"F_Morphotype")]
            public float[] F_Morphotype { get; set; }

            [ColumnName(@"F_Intelligence")]
            public float[] F_Intelligence { get; set; }

            [ColumnName(@"F_HeightPotential")]
            public float[] F_HeightPotential { get; set; }

            [ColumnName(@"F_Age")]
            public float F_Age { get; set; }

            [ColumnName(@"F_Sex")]
            public float[] F_Sex { get; set; }

            [ColumnName(@"F_BehaviorPropension")]
            public float[] F_BehaviorPropension { get; set; }

            [ColumnName(@"S_EyeColor")]
            public float[] S_EyeColor { get; set; }

            [ColumnName(@"S_HairType")]
            public float[] S_HairType { get; set; }

            [ColumnName(@"S_Morphotype")]
            public float[] S_Morphotype { get; set; }

            [ColumnName(@"S_Intelligence")]
            public float[] S_Intelligence { get; set; }

            [ColumnName(@"S_HeightPotential")]
            public float[] S_HeightPotential { get; set; }

            [ColumnName(@"S_Age")]
            public float S_Age { get; set; }

            [ColumnName(@"S_Sex")]
            public float[] S_Sex { get; set; }

            [ColumnName(@"S_BehaviorPropension")]
            public float[] S_BehaviorPropension { get; set; }

            [ColumnName(@"Result")]
            public uint Result { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Attractiveness.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("Result");
            if (labelColumn == null)
            {
                throw new Exception("Result column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<float>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
