
// This file was auto-generated by ML.NET Model Builder. 

using AttractivenessService;

// Create single instance of sample data from first line of dataset for model input
Attractiveness.ModelInput sampleData = new Attractiveness.ModelInput()
{
    F_EyeColor = @"Green",
    F_HairType = @"Ginger",
    F_Handedness = @"Ambidextrous",
    F_Morphotype = @"Endomorph",
    F_Intelligence = @"Science",
    F_HeightPotential = @"Tall",
    F_Age = 79F,
    F_Sex = @"Female",
    F_BehaviorPropension = @"Violent",
    S_EyeColor = @"Brown",
    S_HairType = @"Blonde",
    S_Handedness = @"Ambidextrous",
    S_Morphotype = @"Mesomorph",
    S_Intelligence = @"Art",
    S_HeightPotential = @"Tall",
    S_Age = 77F,
    S_Sex = @"Female",
    S_BehaviorPropension = @"Peaceful",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Result with predicted Result from sample data...\n\n");


Console.WriteLine($"F_EyeColor: {@"Green"}");
Console.WriteLine($"F_HairType: {@"Ginger"}");
Console.WriteLine($"F_Handedness: {@"Ambidextrous"}");
Console.WriteLine($"F_Morphotype: {@"Endomorph"}");
Console.WriteLine($"F_Intelligence: {@"Science"}");
Console.WriteLine($"F_HeightPotential: {@"Tall"}");
Console.WriteLine($"F_Age: {79F}");
Console.WriteLine($"F_Sex: {@"Female"}");
Console.WriteLine($"F_BehaviorPropension: {@"Violent"}");
Console.WriteLine($"S_EyeColor: {@"Brown"}");
Console.WriteLine($"S_HairType: {@"Blonde"}");
Console.WriteLine($"S_Handedness: {@"Ambidextrous"}");
Console.WriteLine($"S_Morphotype: {@"Mesomorph"}");
Console.WriteLine($"S_Intelligence: {@"Art"}");
Console.WriteLine($"S_HeightPotential: {@"Tall"}");
Console.WriteLine($"S_Age: {77F}");
Console.WriteLine($"S_Sex: {@"Female"}");
Console.WriteLine($"S_BehaviorPropension: {@"Peaceful"}");
Console.WriteLine($"Result: {1F}");


var sortedScoresWithLabel = Attractiveness.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

